### ISSUE TITLE
compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by SamuelMarks** [openfoodfacts/openfoodfacts-kotlin#30]
### What
```
> Task :compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: Library/Android/sdk/platforms/android-33/core-for-system-modules.jar.
         > Error while executing process Library/Java/JavaVirtualMachines/openjdk-22.0.2/Contents/Home/bin/jlink with arguments {--module-path .gradle/caches/transforms-3/819e806557193523a1832f0eb24428cd/transformed/output/temp/jmod --add-modules java.base --output .gradle/caches/transforms-3/819e806557193523a1832f0eb24428cd/transformed/output/jdkImage --disable-plugin system-modules}
```

### Steps to reproduce the behavior:
@ 2aa26db [also tried #13]
1. `cd openfoodfacts-kotlin/openfoodfacts-kotlin`
2. `./gradlew publishToMavenLocal`

### Expected behavior
Should work. Also tried with `--stacktrace` but just got a very large output along these lines:
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileDebugJavaWithJavac'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
```

(i.e., not giving anything specific to openfoodfacts-kotlin)

### Platform (Desktop, Mobile, Hunger Games)
 - OS: N/A, host is macOS 15.0 on an M3 with Gradle 8.10.2 and javac 22.0.2
 - Platform Hunger Games

### Part of
N/A

**Comment by naivekook** [comment]
Works fine on my machine with jdk 17. Can you try a lower version of java?

```openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)
```

**Comment by mainrs** [comment]
I can confirm that this only works with JDK17 on my system. I also tried 23 and it failed. For these cases, it would be great to force compilation with a specific toolchain by using the [java toolchain feature](https://docs.gradle.org/current/userguide/toolchains.html). I.e.:

```kotlin


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
```

This forces JDK17 for compilation, making everything work out of the box.
